### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'mcopy'

### ISSUE THREAD

**Issue by stsp** [dosemu2/install-otherdos#10]
dep on mtools is missing.
I added it.
However, there is this code:
```
def verify_system():
    verify_tool('mcopy', 'mtools')
```

It doesn't do the job.
Instead of "please install package",
there is a plain crash.

**Comment by stsp** [comment]
```
Traceback (most recent call last):
  File "/usr/libexec/dosemu-installdos/dosemu-installopendos702", line 42, in <module>
    install_opendos_from_rpm(args.source, args.destination)
  File "/usr/libexec/dosemu-installdos/dosemu-installopendos702", line 26, in install_opendos_from_rpm
    subprocess.run(['mcopy', '-sn', '-i', os.path.join(TMP_DIR, 'hdimage.od') + MTOOLS_HDIMAGE_FILESYSTEM_OFFSET, '::*', drive_root], env={"PATH": os.environ['PATH'], "MTOOLS_LOWER_CASE": '1'})
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mcopy'
```
