### ISSUE TITLE
404 error running dosemu-install3rdpartydos

### ISSUE THREAD

**Issue by wx4cb** [dosemu2/install-otherdos#11]
according to the website the link should be for the latest

http://svardos.org/download/20220412/svardos-20220412-dosemu.zip

```
sbbs@sbbs:~$ sudo dosemu-install3rdpartydos
Installing Caldera OpenDOS 7.02 (1997)
Downloading ftp://ftp.nvg.org/pub/mirrors/metalab.unc.edu/distributions/caldera/updates/OpenLinux/1.3/current/SRPMS/opendos-hdimage-7.02-4.src.rpm...
100%|████████████████████████████| 5191191/5191191 [00:01<00:00, 3032187.67B/s]
Verified checksum /root/.cache/dosemu/opendos702/opendos-hdimage-7.02-4.src.rpm
Installing SvarDOS (rolling release)
Downloading http://svardos.osdn.io/download/svardos-dosemu.zip...
Traceback (most recent call last):
  File "/usr/libexec/dosemu-installdos/dosemu-dlimg", line 124, in <module>
    download_and_process(derive_url_list(url), destination, args.sha256sum if args.sha256sum else [])
  File "/usr/libexec/dosemu-installdos/dosemu-dlimg", line 83, in download_and_process
    destination_files = download_files(imgurls, destination)
  File "/usr/libexec/dosemu-installdos/dosemu-dlimg", line 79, in download_files
    destination_files.append(download_file(imgurl, destination))
  File "/usr/libexec/dosemu-installdos/dosemu-dlimg", line 40, in download_file
    with urllib.request.urlopen(urllib.parse.quote_plus(source, "\./_-:")) as response, open(destination_file, 'wb') as f:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

````

**Comment by stsp** [comment]
Should now be fixed.
@andrewbird maybe add that to
the test-suit?

**Comment by stsp** [comment]
> sbbs@sbbs:~$ sudo dosemu-install3rdpartydos

I wonder if you were successful
in running sbbs under dosemu2.
Some other guy here wasn't.

**Comment by stsp** [comment]
I am a bit ignorant with that topic. :)
I thought its a DOS software.
Just see if you can help here:
https://github.com/dosemu2/dosemu2/discussions/1651
or here:
https://github.com/dosemu2/dosemu2/issues/1706
